services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    
    environment:
      DB_URL: ${DB_URL}

    volumes:
      - ./src:/app
    
    depends_on:
      - db
    
    ports:
      - 8001:8000