services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    
    environment:
      DB_URL: ${DB_URL}
      EMAIL_PASS: ${EMAIL_PASS}
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: "/service-account.json"

    volumes:
      - ./src:/app
      - ./service-account.json:/service-account.json:ro
    
    depends_on:
      - db
    
    ports:
      - 8001:8000