services:
  db:
    image: postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    
    volumes:
      - ./src:/app:ro
    
    depends_on:
      - db
    
    ports:
      - 8001:8000