"""r

Revision ID: 3bf115dcca37
Revises: 0c5593492acd
Create Date: 2025-02-21 06:58:17.925266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bf115dcca37'
down_revision: Union[str, None] = '0c5593492acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adminuser_userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminuser_userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('groupid')
    )
    op.add_column('user', sa.Column('userid', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('user', 'iban',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'id')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('user', 'iban',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'userid')
    op.drop_table('group')
    # ### end Alembic commands ###
