"""Added foreign key in transaction

Revision ID: 3e6917f2a1e7
Revises: 425a198ad24d
Create Date: 2025-02-25 09:30:56.961692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e6917f2a1e7'
down_revision: Union[str, None] = '425a198ad24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('groupid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'group', ['groupid'], ['groupid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'groupid')
    # ### end Alembic commands ###
