"""Test

Revision ID: 425a198ad24d
Revises: d225da7bdc35
Create Date: 2025-02-21 08:01:37.356167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '425a198ad24d'
down_revision: Union[str, None] = 'd225da7bdc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('group',
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adminuser_userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminuser_userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('groupid')
    )
    op.create_table('transaction',
    sa.Column('transactionid', sa.Integer(), nullable=False),
    sa.Column('fromuserid', sa.Integer(), nullable=False),
    sa.Column('touserid', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fromuserid'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['touserid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('transactionid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('group')
    op.drop_table('user')
    # ### end Alembic commands ###
