"""Added Bool for verification in user

Revision ID: 8ce8002cdaad
Revises: e5bf92429b4a
Create Date: 2025-05-04 14:31:28.892361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ce8002cdaad'
down_revision: Union[str, None] = 'e5bf92429b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviting_userid', sa.Integer(), nullable=False),
    sa.Column('invited_userid', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['invited_userid'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['inviting_userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('isVerified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isVerified')
    op.drop_table('friends')
    # ### end Alembic commands ###
