"""added group members

Revision ID: aeec72d465ab
Revises: 3e6917f2a1e7
Create Date: 2025-02-28 07:46:02.812366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aeec72d465ab'
down_revision: Union[str, None] = '3e6917f2a1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupmembers',
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.alter_column('transaction', 'groupid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'groupid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('groupmembers')
    # ### end Alembic commands ###
