"""added fcm_device_token

Revision ID: e5bf92429b4a
Revises: aeec72d465ab
Create Date: 2025-04-16 18:23:34.505744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5bf92429b4a'
down_revision: Union[str, None] = 'aeec72d465ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fcm_device_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fcm_device_token')
    # ### end Alembic commands ###
